# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Monthly Report Execution

on:
  workflow_dispatch:

permissions:  write-all

env:
    CI_COMMIT_MESSAGE: Add Reports 
    CI_COMMIT_AUTHOR: github-actions[bot]
    CI_COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
    BRANCH_NAME: openapi-test

jobs:
  report-execution:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: main

      - name: Git create branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
        working-directory: ./main

      - name: Set Config File
        run: mv config.ini.example config.ini
        working-directory: ./main/eng/edfi-team-automated-reports

      - name: Run Dependabot Script 
        run: |
          python ./eng/edfi-team-automated-reports/github-dependabot-by-project.py

      # - name: Run JiraCloud Script 
      #   run: |
      #     python ./eng/edfi-team-automated-reports/jira-cloud-issues-by-projects.py

      - name: Git add files
        run: |
          git add ./github_dependabot_report.md
        working-directory: ./main
        
      - name: Commit file
        id: commit
        uses: planetscale/ghcommit-action@4131649dbf2fdf1eb34421702972a5af7b0a8731
        with:
          commit_message: "${{ env.CI_COMMIT_MESSAGE }}"
          repo: ${{ github.repository }}
          branch: ${{ env.BRANCH_NAME }}
          file_pattern: '*.yaml *.md'
        working-directory: ./main

      - name: Create PR
        run: gh pr create -B main -H ${{ env.BRANCH_NAME }} --title 'Github Action' --body 'Github Action'
        working-directory: ./main