# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Monthly Report Execution

on:
  schedule:
    - cron: "0 2 1 * *"
  workflow_dispatch:

permissions:  write-all

env:
    CI_COMMIT_MESSAGE: Uploading Reports 
    CI_COMMIT_AUTHOR: github-actions[bot]
    GH_TOKEN_REPO_ACCESS: ${{secrets.GIT_TOKEN}}
    GH_TOKEN_COMMIT_ACCESS: ${{secrets.GIT_TOKEN}}
    API_TOKEN: ${{secrets.API_TOKEN}}
    JIRA_BASE_URL: ${{vars.JIRA_BASE_URL}}
    JIRA_USERNAME: ${{vars.JIRA_USERNAME}}
    GH_PROJECT_LIST: ${{vars.GH_PROJECT_LIST}}
    JIRA_PROJECT_LIST: ${{vars.JIRA_PROJECT_LIST}}
    BRANCH_NAME: report-generated

jobs:
  report-execution:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: main

      - name: Git create branch
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
        working-directory: ./main

      - name: Set Config File
        run: mv config.ini.example config.ini
        working-directory: ./main/eng/edfi-team-automated-reports

      - name: Replace Base Url
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'https://your-domain.atlassian.net'
          replacement-text: ${{ env.JIRA_BASE_URL }}

      - name: Replace Username
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'your-email@example.com'
          replacement-text: ${{ env.JIRA_USERNAME }}

      - name: Replace API Token
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'your-api-token'
          replacement-text: ${{ env.API_TOKEN }}

      - name: Replace Github Token
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'sample-token'
          replacement-text: ${{ env.GH_TOKEN_REPO_ACCESS }}

      - name: Replace Github Token
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'PRJ1,PRJ2'
          replacement-text: ${{ env.JIRA_PROJECT_LIST }}

      - name: Replace Github Token
        uses: richardrigutins/replace-in-files@v2
        with:
          files: './main/eng/edfi-team-automated-reports/config.ini'
          search-text: 'Ed-Fi-Project-1,Ed-Fi-Project-2'
          replacement-text: ${{ env.GH_PROJECT_LIST }}

      - name: Run Dependabot Script 
        run: |
          python ./eng/edfi-team-automated-reports/github-dependabot-by-project.py

      - name: Run JiraCloud Script 
        run: |
          python ./eng/edfi-team-automated-reports/jira-cloud-issues-by-projects.py

      - name: Add and commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ env.CI_COMMIT_MESSAGE }}
          author_name: ${{ env.CI_COMMIT_AUTHOR }}
          add: |
            - './docs/automated-reports/github-dependabot/*.md --force'
            - './docs/automated-reports/jira-issues/*.md --force'
          cwd: './main/'

      - name: Merge reports -> main
        uses: devmasx/merge-branch@master
        with:
           type: now
           from_branch: ${{ env.BRANCH_NAME }}
           target_branch: main
           github_token: ${{ env.GH_TOKEN_COMMIT_ACCESS }}

      - name: Delete branch
        if: always()
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ env.GH_TOKEN_COMMIT_ACCESS }}
          branches: ${{ env.BRANCH_NAME }}
